openapi: '3.0.2'
info:
  title: Payment initiation sandbox API
  version: 1.0.0
paths:
  '/v1.0.0/initiate-payment':
    post:
      summary: Initiate a payment
      description: >-
        This API receives a payment initiation request.
        The API validates the requ`est and returns transaction status
        with signature that the client can verify the response.
      operationId: initiatePayment
      parameters:
      - $ref: '#/components/parameters/X-Request-Id'
      requestBody:
        $ref: '#/components/requestBodies/PaymentInitiationBody'
      responses:
        '201':
          $ref: '#/components/responses/201_PaymentAccepted'
        '400':
          $ref: '#/components/responses/400_PaymentRejected'
        '422':
          $ref: '#/components/responses/422_PaymentRejected'
        '500':
          $ref: '#/components/responses/500_GeneralError'
components:
  parameters:
    X-Request-Id:
      name: X-Request-Id
      in: header
      required: true
      schema:
        $ref: '#/components/schemas/XRequestId'
  requestBodies:
    PaymentInitiationBody:
      description: The payment initiation request body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentInitiationRequest'
  responses:
    201_PaymentAccepted:
      description: The 201 response of the payment initiation endpoint
      headers:
        X-Request-Id:
          $ref: '#/components/headers/X-Request-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentAcceptedResponse'
    400_PaymentRejected:
      description: The 400 response of the payment initiation endpoint
      headers:
        X-Request-Id:
          $ref: '#/components/headers/X-Request-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentRejectedResponse'
    422_PaymentRejected:
      description: The 422 response of the payment initiation endpoint
      headers:
        X-Request-Id:
          $ref: '#/components/headers/X-Request-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentRejectedResponse'
    500_GeneralError:
      description: The 500 response of the payment initiation endpoint
      headers:
        X-Request-Id:
          $ref: '#/components/headers/X-Request-Id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentRejectedResponse'
  headers:
    X-Request-Id:
      description: >-
        Client provided identifier of the request. The same value
        as the request.
      required: true
      schema:
        $ref: '#/components/schemas/XRequestId'
  schemas:
    PaymentInitiationRequest:
      description: The payment initiation request model
      type: object
      required:
      - debtorIBAN
      - creditorIBAN
      - amount
      - endToEndId
      properties:
        debtorIBAN:
          $ref: '#/components/schemas/IBAN'
        creditorIBAN:
          $ref: '#/components/schemas/IBAN'
        amount:
          description: >-
            Amount of the payment initiation
          type: string
          format: "-?[0-9]+(\\.[0-9]{1,3})?"
        currency:
          type: string
          format: "[A-Z]{3}"
          default: EUR
        endToEndId:
          type: string
          description: >-
            Unique identifier per payment initiation request provided
            by the client
    PaymentAcceptedResponse:
      description: Created response. The status shall always be 'Accepted'
      type: object
      required:
      - paymentId
      - status
      properties:
        paymentId:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/TransactionStatus'
    PaymentRejectedResponse:
      description: Created response. The status shall always be 'Rejected'
      type: object
      required: 
      - status
      - reason
      - reasonCode
      properties:
        status:
          $ref: '#/components/schemas/TransactionStatus'
        reason:
          type: string
          description: Human readable reason of the rejection
        reasonCode:
          $ref: '#/components/schemas/ErrorReasonCode'
    IBAN:
      type: string
      format: "[A-Z]{2}[0-9]{2}[a-zA-Z0-9]{1,30}"
    TransactionStatus:
      type: string
      enum:
      - Accepted
      - Rejected
    ErrorReasonCode:
      type: string
      enum:
      - INVALID_REQUEST
      - LIMIT_EXCEEDED
      - GENERAL_ERROR
    XRequestId:
      description: UUID provided by the client to identify the request
      type: string
      format: uuid
